<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\AiModel;
use Illuminate\Database\Seeder;

class AiModelSeeder extends Seeder
{
    public function run(): void
    {
        $models = [
            // Ollama models (local)
            [
                'name' => 'Llama 3.2',
                'description' => 'Latest Llama model, great for general tasks',
                'provider' => 'ollama',
                'model_id' => 'llama3.2',
                'context_window' => 128000,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'medium',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Llama 3.1',
                'description' => 'Powerful Llama model with extended context',
                'provider' => 'ollama',
                'model_id' => 'llama3.1',
                'context_window' => 128000,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'medium',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Mistral',
                'description' => 'Fast and efficient for most tasks',
                'provider' => 'ollama',
                'model_id' => 'mistral',
                'context_window' => 32768,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'fast',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Code Llama',
                'description' => 'Specialized for code generation',
                'provider' => 'ollama',
                'model_id' => 'codellama',
                'context_window' => 16384,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'medium',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Phi-3',
                'description' => "Microsoft's compact but capable model",
                'provider' => 'ollama',
                'model_id' => 'phi3',
                'context_window' => 4096,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'fast',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Qwen 2.5',
                'description' => 'Alibaba model, good tool calling support',
                'provider' => 'ollama',
                'model_id' => 'qwen2.5',
                'context_window' => 32768,
                'supports_tools' => false,
                'supports_vision' => false,
                'speed_tier' => 'medium',
                'cost_tier' => 'free',
                'enabled' => true,
                'is_available' => false,
            ],
            // Groq models (cloud, fast inference)
            [
                'name' => 'Llama 3.3 70B (Groq)',
                'description' => 'Latest Llama 3.3, excellent reasoning',
                'provider' => 'groq',
                'model_id' => 'llama-3.3-70b-versatile',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => false,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Llama 3.1 8B (Groq)',
                'description' => 'Ultra-fast cloud inference, good for quick tasks',
                'provider' => 'groq',
                'model_id' => 'llama-3.1-8b-instant',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => false,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Llama 4 Scout (Groq)',
                'description' => "Meta's newest Llama 4, multimodal capable",
                'provider' => 'groq',
                'model_id' => 'meta-llama/llama-4-scout-17b-16e-instruct',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            // OpenAI models
            [
                'name' => 'GPT-4o',
                'description' => 'Most capable GPT-4 model with vision',
                'provider' => 'openai',
                'model_id' => 'gpt-4o',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'medium',
                'cost_tier' => 'high',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'GPT-4o Mini',
                'description' => 'Faster and cheaper GPT-4o variant',
                'provider' => 'openai',
                'model_id' => 'gpt-4o-mini',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'medium',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'GPT-4 Turbo',
                'description' => 'Previous generation flagship model',
                'provider' => 'openai',
                'model_id' => 'gpt-4-turbo',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'medium',
                'cost_tier' => 'high',
                'enabled' => true,
                'is_available' => false,
            ],
            // Anthropic models
            [
                'name' => 'Claude 3.5 Sonnet',
                'description' => 'Most capable Claude model, excellent reasoning',
                'provider' => 'anthropic',
                'model_id' => 'claude-3-5-sonnet-20241022',
                'context_window' => 200000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'medium',
                'cost_tier' => 'high',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Claude 3 Opus',
                'description' => 'Most powerful Claude model',
                'provider' => 'anthropic',
                'model_id' => 'claude-3-opus-20250219',
                'context_window' => 200000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'slow',
                'cost_tier' => 'high',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Claude 3 Haiku',
                'description' => 'Fast and efficient Claude model',
                'provider' => 'anthropic',
                'model_id' => 'claude-3-haiku-20240307',
                'context_window' => 200000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            // xAI models
            [
                'name' => 'Grok 4.1 Fast Reasoning',
                'description' => 'Latest Grok with enhanced reasoning',
                'provider' => 'xai',
                'model_id' => 'grok-4-1-fast-reasoning',
                'context_window' => 256000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'medium',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Grok 3',
                'description' => 'Powerful Grok model with multimodal support',
                'provider' => 'xai',
                'model_id' => 'grok-3',
                'context_window' => 131000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'medium',
                'cost_tier' => 'medium',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Grok 3 Mini',
                'description' => 'Compact Grok model for quick tasks',
                'provider' => 'xai',
                'model_id' => 'grok-3-mini',
                'context_window' => 131000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            // Gemini models
            [
                'name' => 'Gemini 2.0 Flash',
                'description' => 'Latest Gemini model with massive context',
                'provider' => 'gemini',
                'model_id' => 'gemini-2.0-flash',
                'context_window' => 1000000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Gemini 1.5 Pro',
                'description' => 'Ultra-long context Gemini model',
                'provider' => 'gemini',
                'model_id' => 'gemini-1.5-pro',
                'context_window' => 2000000,
                'supports_tools' => true,
                'supports_vision' => true,
                'speed_tier' => 'medium',
                'cost_tier' => 'medium',
                'enabled' => true,
                'is_available' => false,
            ],
            // Mistral models
            [
                'name' => 'Mistral Large',
                'description' => 'Most capable Mistral model',
                'provider' => 'mistral',
                'model_id' => 'mistral-large-latest',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => false,
                'speed_tier' => 'medium',
                'cost_tier' => 'high',
                'enabled' => true,
                'is_available' => false,
            ],
            [
                'name' => 'Mistral Small',
                'description' => 'Fast and efficient Mistral model',
                'provider' => 'mistral',
                'model_id' => 'mistral-small-latest',
                'context_window' => 128000,
                'supports_tools' => true,
                'supports_vision' => false,
                'speed_tier' => 'fast',
                'cost_tier' => 'low',
                'enabled' => true,
                'is_available' => false,
            ],
        ];

        foreach ($models as $model) {
            AiModel::updateOrCreate(
                ['provider' => $model['provider'], 'model_id' => $model['model_id']],
                $model
            );
        }
    }
}
